### ISSUE TITLE
Species showing multiple times in the 'Species' search

### ISSUE THREAD

**Issue by dkonzek** [USFWS/hunting-opportunities#102]
When I search by species (Moose is a good example), I see the species listed multiple times for each hunt unit.

**Comment by rhewitt22** [comment]
![Screen Shot 2020-02-13 at 12 18 28 PM](https://user-images.githubusercontent.com/3673374/74460492-f739b980-4e5a-11ea-97f2-6a9581a174ed.png)

**Comment by rhewitt22** [comment]
@dkonzek I think this may be an issue with the data. When I search `Moose` I do see a number of duplicates, but when I log the data I'm sending into the template I see that there are thirteen different hunt opportunities for the Alaska Peninsula Refuge, each identifying 'moose', each with a different ObjectID. Are those duplicates? Am I missing something?

**Comment by dkonzek** [comment]
@rhewitt22 There is only 1 Moose record for AK Pen in the related 'Species' table.  It seems to be happening for all of the AK species.

**Comment by dkonzek** [comment]
It seems to be pulling the species record for each of the AK hunt units and listing them all under each Refuge.  Most of the Refuges up there have the same hunt unit name of "Refuge", so if the query is looking for 'HuntUnit' only, that might explain the duplicates.  You might have to use the 'RelateGUID' field.

**Comment by rhewitt22** [comment]
Thanks for setting me down the correct path, I'm making some progress, you're absolutely right in your diagnosis.

**Comment by rhewitt22** [comment]
Yep --- you were 100% correct. I was comparing the HuntUnit field from both the HuntUnit polygon and species table. For Alaska refuges they don't have unique names for hunt units, they're just `Refuge`, so it was inappropriately matching across AK refuges.

**Comment by rhewitt22** [comment]
Closed via #105
