### ISSUE TITLE
Symbolize Huntable Hunt Units Using the Symbol ID Field

### ISSUE THREAD

**Issue by reasterbr** [USFWS/hunting-opportunities#11]
Huntable hunt units need to be symbolized using the Symbol ID field

**Comment by rhewitt22** [comment]
@reasterbr I'm not seeing any information in the [service definition](https://services.arcgis.com/QVENGdaPbd4LUkLV/ArcGIS/rest/services/FWS_NWRS_HQ_PubHuntUnits/FeatureServer/1) as to how I might style this layer.

I see that the Symbol ID field is an integer, I just don't know what those values mean. There is some drawing information associated with this layer, which is how I'm currently styling the layer (I think!).

**Comment by reasterbr** [comment]
If Huntable = No, then the existing symbology (red) can be used.

If Huntable = Yes, then use the Symbol ID field to uniquely symbolize the polygons

**Comment by rhewitt22** [comment]
Use the Symbol ID field to uniquely symbolize the polygons how? Is there a color or style to correspond with each Symbol ID, and if so, where can I find them?

**Comment by reasterbr** [comment]
No, there is not a style to use.  I was hoping there was a color scheme you could utilize that would be based off from the unique value in the Symbol ID field.  It is unique by refuge.

**Comment by rhewitt22** [comment]
We want to make clear where one hunt unit begins and one ends.

1. We could add a border between hunt units to show a boundary <--- test this option first
2. We could color the hunt units differently

The values in the Symbol ID is unique within a refuge, but not across the whole dataset.

**Comment by rhewitt22** [comment]
Closed via #60
