### ISSUE TITLE
Raster Tiles for AK

### ISSUE THREAD

**Issue by dkonzek** [USFWS/hunting-opportunities#112]
Here is the url for the AK Raster Tiles:

https://tiles.arcgis.com/tiles/QVENGdaPbd4LUkLV/arcgis/rest/services/2019_2020HuntUnitsAK_Tile/MapServer

Tiles were created for scales 1 - 10 (1:288,895).  Only AK is included.  Tiles do not contain any attributes, so they are not clickable.

**Comment by rhewitt22** [comment]
I don't think these tiles ever finished publishing. I think we have what we need from the simplified feature layer. Closing, this is related to #104, check there for updates.
