### ISSUE TITLE
Problem with Related Huntable Species Table 

### ISSUE THREAD

**Issue by reasterbr** [USFWS/hunting-opportunities#13]
The related Huntable Species table in NOT joining properly with the hunt units polygon data.  For example, there are not feral hogs at Ridgefield NWR.  You'll need to look into this with Dan.

**Comment by rhewitt22** [comment]
Addressed by #25; will republish and request Richard or someone else tests to verify.

**Comment by rhewitt22** [comment]
@reasterbr would you mind taking a look and verifying I have this right?

**Comment by rhewitt22** [comment]
Closing for now as I believe this is resolved. We can reopen if necessary.
