### ISSUE TITLE
Add Labels to Hunt Units once Zoomed-in

### ISSUE THREAD

**Issue by reasterbr** [USFWS/hunting-opportunities#14]
Please add labels to the huntable hunt hunts once zoomed-in.

**Comment by rhewitt22** [comment]
Labels can be added with [L.tooltip](https://leafletjs.com/reference-1.6.0.html#tooltip). Wondering if this can be scale dependent...

**Comment by rhewitt22** [comment]
There's no built-in way to do this scale-dependent. We can manually achieve this by querying the map's zoom level on the `zoomend` event.

**Comment by rhewitt22** [comment]
The hunt unit names aren't that great. I'm publishing this change, would like some review to determine if this is really what we want.

We can also configure labels to only display when the user hovers their mouse over a given hunt unit...

**Comment by rhewitt22** [comment]
Addressed by #29.

![Screen Shot 2020-01-03 at 10 42 20 AM](https://user-images.githubusercontent.com/3673374/71732707-f4888500-2e15-11ea-9ba3-0b4b66900c32.jpg)

Some thoughts:

1. The labels can obscure the amenity icons
1. We can increase the opacity of the labels if needed
1. We can change the zoom level at which the labels are displayed (currently at level 12)
1. We can display the labels only when a user hovers over a certain polygon

**Comment by rhewitt22** [comment]
Closing for now as this is resolved. We can reopen or create a new issue if the labels need work.
