### ISSUE TITLE
Add Special Regulations Hyperlink

### ISSUE THREAD

**Issue by reasterbr** [USFWS/hunting-opportunities#16]
If special regulations exist for huntable species, add the URL Dan and Richard provided to the station's  hunting page.

**Comment by reasterbr** [comment]
This should open in a new browser tab.

**Comment by rhewitt22** [comment]
Need to combine refuge hunt opportunity data with info on specific hunt unit/huntable species in order to make this work.

**Comment by rhewitt22** [comment]
@reasterbr is the URL you're referring to in the 'UrlHunting' field?

**Comment by rhewitt22** [comment]
- [x] Update list of huntable species after clicking on a hunt unit
- [ ] Update list of hunt units after selecting a huntable species from the drop-down

**Comment by reasterbr** [comment]
Yes, the "UrlHunting" field

**Comment by rhewitt22** [comment]
Addressed by #74
