### ISSUE TITLE
Only Show Relevant Visitor Service Amenities Items 

### ISSUE THREAD

**Issue by reasterbr** [USFWS/hunting-opportunities#19]
Only show those visitor service amenities pertinent to hunters.  For example, you might not want to show "Interpretive Exhibits".  Kristin and Kate would have an opinion here.

**Comment by rhewitt22** [comment]
Need more info as to what amenities are deemed appropriate for hunters. Here is the list of possible amenity categories according to ArcGIS Online:

- Airport (36) - A tract of land or water with facilities for the landing, takeoff, shelter, supply, and repair of aircraft, especially one used for receiving or discharging passengers and cargo at regularly scheduled times. 
- Amphitheater (26) - A designated area with seating where participants can gather for movies, nature talks, interpretive presentations, etc. 
- Beach Access (35) - Primary access to the part of the shore of an ocean, sea, large river, lake, etc., washed by the tide or waves. 
- Boardwalk/Footbridge (47) - An elevated structure, between two points at a height above the ground, designed for pedestrian. It enables pedestrians to cross wet, fragile, or marshy land. 
- Boat Launch (1) - Ramp used to launch and land boats. 
- Bus Stop/Shuttle Stop (30) - Bus or shuttle stop. 
- Cabin (2) - A small, four-walled structure, made of wood and situated in a wild or remote area. 
- Campground (3) - A place used for camping equipped with facilities (e.g., pads, cooking grills, water, and bathrooms.) 
- Cemetery (38) - An area set apart for or containing graves, tombs, or funeral urns, especially one that is not a churchyard. 
- Community Center (41) - A place where people from a particular community can meet for social, educational, or recreational activities. 
- Dispersed Campsites (34) - Campsites outside a designated campground where facilities (e.g., toilets, picnic tables, trash cans, treated water, and fire grates) are not available. 
- Driving Tour (4) - A driving route particularly suited for refuge touring which may contain interpretive signage. 
- Entrance Station (32) - Primary entry location where entry fees are paid and information is provided. 
- Ferry (28) - A boat or ship for conveying passengers and goods, especially over a relatively short distance and as a regular service. 
- Fish Cleaning (29) - A location designated for the proper cleaning and disposal of fish carcasses. 
- Fish Hatchery (43) - A place for artificial breeding, hatching, and rearing through the early life stages of finfish and shellfish. 
- Fish Ladder (44) - A series of pools built like steps to enable fish to bypass a dam or waterfall. 
- Fishing (5) - A location that provides fishing access. 
- Fishing Platform (6) - A platform extending from shore over the water to provide fishing access. 
- Gate (7) - Structure that provides an opening for access through a fence. 
- Hand Launch/Small Boat Launch (8) - A location where a small boat (e.g., canoe, kayak) may be launched by hand. 
- Hunter Check-in Station (9) - A location where hunters must show valid hunting licenses, conservation stamps, etc., and display harvested game. 
- Hunting Blind (10) - A cover device for hunters, designed to reduce the chance of detection. 
- Information (11) - A building designed specifically for the purpose of orienting visitors to resources and programs and providing other services to support visitation. Usually includes exhibits and restrooms; sometimes gift shops. 
- Interpretive Exhibit (12) -  Open‐air structure used for interpretive media such interpretive panels, wayside exhibits, maps, brochure racks, or other information. 
- Lighthouse (23) - A tower building displaying a light or lights for the guidance of maritime vessels. 
- Marina (24) - A marina is a dock or basin with moorings and supplies for yachts and small boats. 
- Metro (31) - Metro or train stop. 
- Museum (25) - A building used to store, protect and/or display museum property. 
- Observation Blind (13) - A cover device for wildlife viewing, designed to reduce the chance of detection. 
- Observation Deck (15) - Raised structure used to provide enhanced viewing. 
- Parking (16) - A flat, single level, designated area used for temporary occupation of vehicles. 
- Pavilion (19) - An open‐air structure with a roof to protect occupants from sun or rain. 
- Picnic Area (17) - A designated area that may include picnic tables, solid waste container, restroom, parking area, etc. 
- Point of Interest (40) - A specific point location that someone may find useful or interesting. An example is the location of a historic site or natural wonder. 
- Refuge Office (33) - Ranger Station, Headquarters (not visitor contact station or visitor center). 
- Restroom (18) - A building intended primarily for public use for defecation and urination, washing, and sometimes showering. 
- Sanitary Disposal Station (27) - A facility intended to receive the discharge of wastewater from a holding tank installed in any recreational vehicle. 
- Scenic Viewpoint (14) - A sightseeing location where people can view and photograph scenery. 
- School (42) - An institution for educating children. 
- Store (39) - An establishment where merchandise and/or food is sold, usually on a retail basis. 
- Trailhead (20) - An access point to a trail system. 
- Tunnel (46) - An artificial underground passage, especially one built through a hill or under a building, road, or river. 
- Water Trailhead (45) - An access point to a water trail system. 
- Wildlife Viewing (22) -  A location where people can view and photograph wildlife in their natural habitat.

**Comment by reasterbr** [comment]
This was more of a comment for Kristen and Kate.  Hoping we just show those amenities they feel would be relevant to hunters.  I'll bring this up on the next call.

**Comment by kgilbert-design** [comment]
Here is the list of Amenities to include:

Airport (36) - A tract of land or water with facilities for the landing, takeoff, shelter, supply, and repair of aircraft, especially one used for receiving or discharging passengers and cargo at regularly scheduled times.
Beach Access (35) - Primary access to the part of the shore of an ocean, sea, large river, lake, etc., washed by the tide or waves.
Boat Launch (1) - Ramp used to launch and land boats.
Cabin (2) - A small, four-walled structure, made of wood and situated in a wild or remote area.
Campground (3) - A place used for camping equipped with facilities (e.g., pads, cooking grills, water, and bathrooms.)
Dispersed Campsites (34) - Campsites outside a designated campground where facilities (e.g., toilets, picnic tables, trash cans, treated water, and fire grates) are not available.
Entrance Station (32) - Primary entry location where entry fees are paid and information is provided.
Ferry (28) - A boat or ship for conveying passengers and goods, especially over a relatively short distance and as a regular service.
Gate (7) - Structure that provides an opening for access through a fence.
Hand Launch/Small Boat Launch (8) - A location where a small boat (e.g., canoe, kayak) may be launched by hand.
Hunter Check-in Station (9) - A location where hunters must show valid hunting licenses, conservation stamps, etc., and display harvested game.
Hunting Blind (10) - A cover device for hunters, designed to reduce the chance of detection.
Information (11) - A building designed specifically for the purpose of orienting visitors to resources and programs and providing other services to support visitation. Usually includes exhibits and restrooms; sometimes gift shops.
Marina (24) - A marina is a dock or basin with moorings and supplies for yachts and small boats.
Parking (16) - A flat, single level, designated area used for temporary occupation of vehicles.
Refuge Office (33) - Ranger Station, Headquarters (not visitor contact station or visitor center).
Restroom (18) - A building intended primarily for public use for defecation and urination, washing, and sometimes showering.
Sanitary Disposal Station (27) - A facility intended to receive the discharge of wastewater from a holding tank installed in any recreational vehicle.
Trailhead (20) - An access point to a trail system.
Water Trailhead (45) - An access point to a water trail system.

**Comment by rhewitt22** [comment]
Closed via #78
