### ISSUE TITLE
Swap "Species" for "Label" in hunt unit results

### ISSUE THREAD

**Issue by reasterbr** [USFWS/hunting-opportunities#22]
Please list the special hunt information in the huntable species table.

**Comment by rhewitt22** [comment]
What specifically are you wanting me to include here? Below is a snapshot of some of the data available for display:

![Screen Shot 2019-12-31 at 11 04 45 AM](https://user-images.githubusercontent.com/3673374/71626883-60bc7c00-2bbd-11ea-8222-371049535dc9.jpg)

**Comment by reasterbr** [comment]
It would be the Access field.  For example, at Sherburne NWR, on "Area B", there are disabled and youth special hunt opportunities.

**Comment by rhewitt22** [comment]
There may be multiple hunts for the same species on a single hunt unit targeting different demographic communities.

For example, we might have multiple hunts for deer in the same unit:

1. Alligator - Limited: Youth
2. Alligator - Limited: Veteran
3. Alligator - Limited: General

**Comment by rhewitt22** [comment]
Closed via #62
