### ISSUE TITLE
Side Bar info

### ISSUE THREAD

**Issue by dkonzek** [USFWS/hunting-opportunities#51]
When I view a list of refuges in the sidebar (if I search by state for example), I think it may be useful for the viewer if a few functions were added:

- When I click on the blue refuge name, can the same information popup in the sidebar as if I were to click on the centroid symbol on the map (hunting description, hunt units, etc)? 
- When I click on the refuge name, it might also be helpful if the map zoomed to the refuge.  
- ~~This would likely require a 'back' navigation feature in the side bar also. (see #54)~~

**Comment by rhewitt22** [comment]
Duplicate of #38
