### ISSUE TITLE
Zoom to hunt unit not functioning for Special Hunts search

### ISSUE THREAD

**Issue by dkonzek** [USFWS/hunting-opportunities#52]
When I am looking at the Special Hunts, it seems that the 'zoom' button may not be functioning?  I am looking at Veterans Hunts, and when I click on the + for Blackwater, nothing happens.

**Comment by rhewitt22** [comment]
Hey @dkonzek I think I forgot to upload a recent change. Reload the page or clear our browser's cache, I think I have this one fixed.

**Comment by dkonzek** [comment]
Yes, it is working now, but I noticed another issue.  I clicked on the centroid dot for Arapaho NWR, and then clicked on the zoom button for unit B.  This zooms me in and outlines Unit B.  When Unit B is outlined, I am not able to click on it to view the species info.  When I click on the zoom button, it may be helpful for the sidebar to automatically switch to the species info in addition to zooming to the unit.  This would require a 'back button' in the side bar for navigating back to the main refuge content.  Is this possible?

**Comment by rhewitt22** [comment]
This is a number of different issues wrapped up into one. 

1. The initial zoom-to function is restored. 
2. There's a separate issue for a back button.
3. Creating a separate issue for triggering hunt unit info when you click the zoom button
