### ISSUE TITLE
Improve design of individual refuge in sidebar

### ISSUE THREAD

**Issue by rhewitt22** [USFWS/hunting-opportunities#7]
These items appear in a list in search results.

![Screen Shot 2019-12-20 at 10 14 08 AM](https://user-images.githubusercontent.com/3673374/71264202-8c17af00-2311-11ea-8325-3f044e4128da.jpg)

**Comment by kgilbert-design** [comment]
Here are the design specifications for items that appear in the search results. 

![RefugeSideBar-02](https://user-images.githubusercontent.com/59093595/71269063-680d9b00-231c-11ea-94cf-46a00bbcc7d9.png)

Colors: 
Classic Blue #0f4c81 (Headings, and any other major use of color)
FWS Orange: # f0af3b (dot, accent color )
Gray: #848484  (icons)

Fonts (same as new Drupal site)
Sans Source Pro (search results and body copy)
Semibold (Refuge name in Search Results)



Merriweather( H1- Find Your Hunt )

**Comment by rhewitt22** [comment]
- [x] Update blue
- [x] Update orange
- [x] Update gray
- [ ] Include source sans pro

**Comment by rhewitt22** [comment]
Closed by #27
